project_id = "qbkgyervpdcgzhojqfch"

[functions.send-appointment-reminders]
verify_jwt = false

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-booking-confirmation-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-test-sms]
verify_jwt = false
