// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbkgyervpdcgzhojqfch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFia2d5ZXJ2cGRjZ3pob2pxZmNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjI4MDYsImV4cCI6MjA2ODQ5ODgwNn0.hvoQXgUUh03xNzS4d9exCS34fFvaZYLvfP3TqPL7tkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});